### ISSUE TITLE
🌈CSS 动态文字彩虹效果

### ISSUE THREAD

**Issue by raxxarr** [raxxarr/note#1]
<img width="500" alt="2018-09-06 11 30 07" src="https://user-images.githubusercontent.com/7265362/45168008-eda32f80-b22c-11e8-91c7-7b09106b2361.png">

[动态效果看这里](https://codepen.io/raxxarr/pen/pOWwwb/)

要实现这个效果，需要解决两个问题：
1. 渐变色文字
2. 平滑变换颜色

## 渐变色文字
单纯的 `color` 属性是无法实现的，我们需要用到一个属性：`background-clip`，它可以用来规定背景如何填充相应区域。

该属性有以下可用 value:

```css
background-clip: border-box; // 将背景填充到边框外（但是会被边框遮住）
```
![clip_border](https://user-images.githubusercontent.com/7265362/45168599-3e675800-b22e-11e8-8145-261496466259.png)

```css
background-clip: padding-box; // 背景填充到 padding 外边界
```
![clip_border](https://user-images.githubusercontent.com/7265362/45168599-3e675800-b22e-11e8-8145-261496466259.png)
*视觉表现和上面的一样，因为边框不是透明的*

```css
background-clip: content-box; // 背景填充到 content 外边界
```
![clip_content](https://user-images.githubusercontent.com/7265362/45168772-ab7aed80-b22e-11e8-9ecf-28f3e4309ee4.png)
![clip_content_with_notion](https://user-images.githubusercontent.com/7265362/45168783-b2096500-b22e-11e8-99fc-ad9b1e7f091b.png)

```css
background-clip: text; //  只填充 text（但是它会被文字 color 遮住，毕竟是「背景」嘛，所以要看出效果，需要文字透明）
```
value = text 有一定的兼容性问题，具体[见这里](https://caniuse.com/#search=background-clip)，FF、Chrome、Safari 支持 `-webkit-background-clip: text;`。

![clip_text](https://user-images.githubusercontent.com/7265362/45169150-92267100-b22f-11e8-892a-f011fcaec32d.png)

所以，第一步思路有了：彩色文字可以使用 `-webkit-background-clip: text` 属性，然后给个彩色背景，颜色就能按文字的形状填充了。

**那么渐变颜色怎么来的呢？**
想到有一个 `linear-gradient` 属性，线性渐变，它可以实现渐变颜色。
所以使用 `background-color: linear-gradient()` 就好啦？
No.
MDN 有以下说明：
> 提示：由于 \<gradient> 数据类型系 \<image> 的子数据类型，\<gradient> 只能被用于 \<image> 可以使用的地方。因此，linear-gradient() 并不适用于 background-color 以及类似的使用 \<color> 数据类型的属性中。
既然只能用于 image 相关数据，那么我们就可以使用 `background-image` 了。
```css
background-image: linear-gradient(to right, yellow, red);
```
![text-gradient](https://user-images.githubusercontent.com/7265362/45169505-563fdb80-b230-11e8-88a7-fa0a37c5d753.png)

至此，第一个问题解决，我们有了一个彩虹色的文字。

## 如何让彩虹色动起来

首先想到的是，在 `animation` 中分几个节点，依次让颜色向后偏移一位，比如：

```css
@keyframes rainbow {
    0% {
        background-image: linear-gradient(to right, red, orange, yellow);
    }
    50% {
        background-image: linear-gradient(to right, orange, yellow, red);
    }
    100% {
        background-image: linear-gradient(to right, yellow, red, orange);
    }
}
```
渲染结果发现，颜色只会生硬地变化，没有过渡效果。
事实上，`animation` 中两个状态之间的过渡称为**隐式过渡（implicit transitions）**，因为开始与结束之间的状态由浏览器决定。所以，哪些属性可以产生过渡，由浏览器决定并实现。
[这里](https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_animated_properties) 有一份支持过渡的属性列表（列表可能会变化）,查阅发现，并没有 `background-image` 属性。

仔细观察🌈动效发现，它其实是每个颜色都往同一个方向运动，因此我们想到是不是可以通过改变彩虹背景的位置来实现呢？
也就是说，可以**使用 animation 改变 background-image 的位置**，背景图位置怎么变？当然是 `background-position`，查阅 [列表](https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_animated_properties) 发现支持过渡，搞起。

**假设文字是从左向右的渐变背景，宽度是 100px。那么我们只需要把背景图从初始的 0px 位置移动到 100px 的位置，就可以完成一次渐变。**

```css
@keyframes move {
    from {
        background-position: 0;
    }

    to {
        background-position: 100px;
    }
}

background-size: 100px; // 注意这个需要是文字的实际宽度，而不是容器的宽度，因为背景图的实际展示区域只在文字上
animation: move 1s linear infinite;
```
![clip_no](https://user-images.githubusercontent.com/7265362/45171143-327e9480-b234-11e8-91bb-9926c2b63d3c.png)
[动态效果看这里](https://codepen.io/raxxarr/pen/vzeJoy)
动起来了！ 但是……，怎么有点不对劲。开始和结束的过渡太生硬了。我们把开始和结束的颜色设成一样的就完美了。

```css
background-image: linear-gradient(to right, yellow, red, yellow);
```

**完整代码**
```html
<style>
    @keyframes bling {
        from {
            background-position: 0;
        }
        to {
            background-position: 1063px;
        }
    }
    .rainbow-text {
        display: inline-block;
        position: relative;
        font-weight: 500;
        font-size: 100px;
        color: transparent;
        animation: bling 3s linear infinite;
        background-image: linear-gradient(to right, red, orange, yellow, lightgreen, skyblue, lightgreen, yellow, red);
        -webkit-background-clip: text;
        background-size: 1063px;
    }
</style>
<p class="rainbow-text">See my rainbow color!</p>
```

## 如果斜向渐变呢？
使用改变 position 的方法，当 linear-gradient 是斜向的时候会有比较生硬的过渡，如何解决这个问题呢？
是时候祭出大杀器了：`filter: hue-rotate(angle);`

这就是今天的主角了：**色相**

**什么是色相**
其实就是*出卖色相*的色相。咳咳，色相通俗来说就是颜色的相貌，一眼看上去是什么样子的。
>在不同波长的光照下，人眼所感觉不同的颜色，如红色、蓝色、黄色

可以参考 [wiki 的解释](https://zh.wikipedia.org/wiki/%E8%89%B2%E7%9B%B8) 。

以下是一个色相轮（条），0 是红色，当我们不断偏移它的角度，60、120、180... 会逐渐经历红橙黄绿蓝靛紫，正好是我们要的彩虹颜色，转一圈 360° 后，又回到红色。如果把它首尾连成一个圈，会发现每个颜色轮转 360°（或它的倍数）都会回到初始的颜色。

![hue](https://user-images.githubusercontent.com/7265362/45171582-5f7f7700-b235-11e8-8157-7007baa1c4b8.png)

那么思路就清晰了，我们只需要让彩虹色按照色相值来过渡，那么让每个颜色的色相轮转 360 度，必然能够按照色相轮的顺序（也就是我们彩虹的顺序）变化一圈，然后回到初始的颜色。

先修改彩虹颜色，可以按照这个表来：
![hue-ref](https://user-images.githubusercontent.com/7265362/45171677-95246000-b235-11e8-8928-3d7cabd35ca3.png)

```css
background-image: linear-gradient(to right bottom, rgb(255,0,0), rgb(255,128,0), rgb(255,255,0), rgb(0,255,0), rgb(0,255,128), rgb(0,255,255), rgb(0,128,255), rgb(0,0,255), rgb(128,0,255), rgb(255,0,255), rgb(255,0,128));
```
然后让他们动态轮转一圈
```css
@keyframes hue {
    from {
        filter: hue-rotate(0);
    }

    to {
        filter: hue-rotate(360deg); // 这里正值就是正着轮转，负值就是反着轮转。视觉效果上就是向左上滚动和向右下滚动的区别。
    }
}

animation: hue 2s linear infinite;
```
![res_1](https://user-images.githubusercontent.com/7265362/45171809-fea46e80-b235-11e8-82eb-8b39f08f24d2.png)
![red_2](https://user-images.githubusercontent.com/7265362/45171816-019f5f00-b236-11e8-8f19-d40a87deecdb.png)

Boom. 大功告成。

[动态效果看这里](https://codepen.io/raxxarr/pen/pOWwwb/)

**源代码**
```css
@keyframes hue {
    from {
        filter: hue-rotate(0);
    }

    to {
        filter: hue-rotate(360deg);
    }
}

.rainbow-text {
    display: inline-block;
    position: relative;
    font-weight: 500;
    font-size: 100px;
    color: transparent;
    animation: hue 2s linear infinite;
    background-image: linear-gradient(to right bottom, rgb(255,0,0), rgb(255,128,0), rgb(255,255,0), rgb(0,255,0), rgb(0,255,128), rgb(0,255,255), rgb(0,128,255), rgb(0,0,255), rgb(128,0,255), rgb(255,0,255), rgb(255,0,128));
    -webkit-background-clip: text;
}
```

## 一点延伸
**色相(hue)、明度(brightness)、饱和度(saturation)** 是颜色的三个基本概念，有关他们之间的关系，有一个简单的示意图：
![circ](https://user-images.githubusercontent.com/7265362/45171930-5216bc80-b236-11e8-88ea-2a1241d95a2f.png)
*图自zhihu.com*

红、黄、绿、青、蓝 这一圈是色相；
色相轮上的任何颜色，明度 100% 时变成白色，0% 时变成黑色；
色相轮上的任何颜色，饱和度 100% 是它本身，0% 是没有颜色的灰色。

[可参考](https://zhuanlan.zhihu.com/p/30409532)
